### ISSUE TITLE
registerGenBlockRep

### ISSUE THREAD

**Issue by Playsoon** [superckl/BiomeTweaker#70]
Using BiomeTweaker-1.8-2.0.168 for Minecraft 1.8 using Forge1.8-11.14.4.1563

I've looked this up and tried a lot of different things to change stone and have the grass and dirt gen too, but it doesn't happen.

    candoria = forAllBiomes()
    candoria.set("topBlock", "candoria:candoria_grass")
    candoria.set("fillerBlock", "candoria:candoria_dirt")
    candoria.registerGenBlockRep("minecraft:stone", "candoria:candoria_cake_layer_1")
    candoria.addActualFillerBlock("candoria:candoria_cake_layer_1")
    candoria.removeFeature("LAVA")
    candoria.removeFeature("BEACH")

If I don't change stone the grass and dirt spawn fine. Changing the stone stops grass and dirt from generating.

The candoria mod currently only adds 3 blocks. Here's the link if you want try my script with my mod.
http://www.mediafire.com/download/4aca6zci54909nj/candoria.zip

**Comment by superckl** [comment]
Yeah, that feature is broken in that release. It's fixed in the latest build (177+). You can find all the builds here:

http://jenkins.superckl.me/job/BiomeTweaker%201.8/

**Comment by Playsoon** [comment]
Downloaded BiomeTweaker-1.8-2.0.181.jar and am still getting the same effect.

![Image](http://oi65.tinypic.com/rlaq6h.jpg)

**Comment by superckl** [comment]
Found the issue. Turns out I hard-coded deobf names into the class transformers, causing a few features to not work in a obfuscated environment. The latest build should now work. Let me know how it goes.

http://jenkins.superckl.me/job/BiomeTweaker%201.8/183/

**Comment by Playsoon** [comment]
Works great now. Thanks.

Next, I've noticed it only changes small portions of the biomes below.

Extreme Hills
Extreme Hills+
Extreme Hills+ M

**Comment by superckl** [comment]
Known issue, last item of #67
