### ISSUE TITLE
1.8.9 Crash

### ISSUE THREAD

**Issue by comfysquirrel** [superckl/BiomeTweaker#84]
http://pastebin.com/A2udaCFM
- Forge 1.8.9-11.15.1.1855
- BiomeTweaker 1.8.9-2.1.197

**Comment by superckl** [comment]
Fixed in 247ca907894b7b49a2aee4f738526799e9e89d25

Releasing to CurseForge now.

**Comment by comfysquirrel** [comment]
Unfortunately, it still crashes with build 198.
http://pastebin.com/MdGztwJD

**Comment by superckl** [comment]
Strange. I tested the new build. I'll keep looking into it.

**Comment by superckl** [comment]
Should be fixed in build 200 now. Sorry. There was an issue with the build server thinking the resources were up to date when they were not.

**Comment by comfysquirrel** [comment]
Yep, it works now! Thanks!
